#!/usr/bin/env python3
"""Render every number the paper quotes, straight from the frozen artifacts.

The paper has already shipped one hand-typed number that was wrong (the pre-onset
residual was written as 2 disturbed environment pairs when the artifacts say 4),
so the rule now is: if a number appears in a table, an abstract, a caption or a
results sentence, it is emitted here and pasted, never retyped.

Reads, and reads nothing else:
  reliability_eval/<study>/combined_summary_n5.json   registered estimand + gate
  reliability_eval/<study>/onset_residual_audit_n5.json   residual audit
  analysis/selection_bias/process_level.json          process-level inference

Two inferential levels appear side by side throughout and are LABELLED, because
they answer different questions and the paper's one real inferential defect was
letting the narrower one stand in for the wider one:

  block bootstrap    resamples blocks within each process, never processes.
                     Conditional on the process seeds actually run.
  process level      mean of the per-process means, Student t on n processes.
                     Carries between-process variance. This is the one a
                     reviewer asking "would it replicate on new seeds" wants.

Usage:
  PYTHONPATH=src python scripts/paper_numbers.py            # markdown to stdout
  PYTHONPATH=src python scripts/paper_numbers.py --out paper/numbers.md
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
STUDY = REPO / "reliability_eval/causal_viability_replication_v2"
CELLS = ("stand_motor", "stand_obs", "walk_motor", "walk_obs")
FAMILIES = ("motor", "obs")


def pp(x: float) -> float:
    return x * 100


def ci(entry: dict, key: str = "mean_difference") -> str:
    return "%+.2f [%+.2f, %+.2f]" % (
        pp(entry[key]), pp(entry["ci_low"]), pp(entry["ci_high"])
    )


def proc(entry: dict) -> str:
    if entry.get("lo_pp") is None:
        return "%+.2f [undefined at n=%d]" % (entry["point_pp"], entry["n_processes"])
    return "%+.2f [%+.2f, %+.2f]" % (entry["point_pp"], entry["lo_pp"], entry["hi_pp"])


def zero(entry: dict) -> str:
    return "excludes 0" if entry["excludes_zero"] else "**includes 0**"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--summary", default=str(STUDY / "combined_summary_n5.json"))
    ap.add_argument("--residual", default=str(STUDY / "onset_residual_audit_n5.json"))
    ap.add_argument("--process", default=str(REPO / "analysis/selection_bias/process_level.json"))
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    S = json.loads(Path(args.summary).read_text())
    R = json.loads(Path(args.residual).read_text())["summary"]
    P = json.loads(Path(args.process).read_text())

    n_proc = P["n_processes"]
    n_blocks = P["n_blocks_disturbed"]
    per_cell = n_blocks // len(CELLS)
    L: list[str] = []
    add = L.append

    add("<!-- GENERATED by scripts/paper_numbers.py. Do not hand-edit; regenerate. -->")
    add("")
    add("# Phoenix paper numbers, rendered from artifacts")
    add("")
    add(f"- processes (independent process seeds): **{n_proc}**")
    add(f"- protocols: **{n_proc * len(CELLS)}**, independent blocks: **{P['n_blocks_total']}**")
    add(f"- disturbed blocks: **{n_blocks}** ({per_cell} per cell)")
    add(f"- disturbed environment pairs: **{P['residual']['env_pairs_disturbed']:,}**"
        f" (all pairs: {P['residual']['env_pairs_all']:,})")
    add("")

    add("## Table II. Primary outcome, four cells")
    add("")
    add("| cell | blocks | effect, block bootstrap | effect, process level (n=%d) | process level |" % n_proc)
    add("|---|---|---|---|---|")
    for c in CELLS:
        add("| %s | %d | %s | %s | %s |" % (
            c, per_cell, ci(S["pooled_cells"][c]), proc(P["cells_full"][c]),
            zero(P["cells_full"][c])))
    add("")
    add("Per-process effects, pp (the %d numbers each process-level interval is built from):" % n_proc)
    add("")
    for c in CELLS:
        add("- `%s`: %s" % (c, ", ".join(
            "%+.2f" % v for v in P["cells_full"][c]["process_effects_pp"])))
    add("")

    add("## Table IIb. Fault family, the level the registered gate criterion is defined on")
    add("")
    add("| family | blocks | block bootstrap | process level (n=%d) | process level |" % n_proc)
    add("|---|---|---|---|---|")
    for f in FAMILIES:
        add("| %s | %d | %s | %s | %s |" % (
            f, n_blocks // 2, ci(S["pooled_fault_families"][f]),
            proc(P["families_full"][f]), zero(P["families_full"][f])))
    inter = S["fault_by_treatment_interaction_obs_minus_motor"]
    add("| **interaction (obs minus motor)** | %d | %s | %s | %s |" % (
        n_blocks, ci(inter), proc(P["interaction_full"]), zero(P["interaction_full"])))
    add("")

    add("## Table III. Pre-onset negative control (true value is exactly zero)")
    add("")
    add("| cell | block bootstrap | process level (n=%d) | must include 0 |" % n_proc)
    add("|---|---|---|---|")
    for c in CELLS:
        e = S["pooled_pre_onset_negative_control_cells"][c]
        p = P["pre_onset_control_cells"][c]
        add("| %s | %+.3f [%+.3f, %+.3f] | %+.3f [%+.3f, %+.3f] | %s |" % (
            c, pp(e["mean_difference"]), pp(e["ci_low"]), pp(e["ci_high"]),
            p["point_pp"], p["lo_pp"], p["hi_pp"],
            "PASS" if not p["excludes_zero"] else "**FAIL**"))
    add("")

    add("## Table IIIb. Leak-free subset (blocks the residual provably did not reach)")
    add("")
    add("| cell | subset blocks | block bootstrap | process level (n=%d) | process level |" % n_proc)
    add("|---|---|---|---|---|")
    for c in CELLS:
        s = P["cells_leakfree"][c]
        bb = s["block_bootstrap"]
        add("| %s | %d of %d | %+.2f [%+.2f, %+.2f] | %s | %s |" % (
            c, P["leakfree_counts"][c]["leakfree"], P["leakfree_counts"][c]["total"],
            bb["point_pp"], bb["lo_pp"], bb["hi_pp"], proc(s), zero(s)))
    add("")
    add("Leak-free subset at the fault-family level:")
    add("")
    add("| family | subset blocks | block bootstrap | process level (n=%d) | process level |" % n_proc)
    add("|---|---|---|---|---|")
    for f in FAMILIES:
        s = P["families_leakfree"][f]
        bb = s["block_bootstrap"]
        add("| %s | %d | %+.2f [%+.2f, %+.2f] | %s | %s |" % (
            f, s["n_blocks"], bb["point_pp"], bb["lo_pp"], bb["hi_pp"], proc(s), zero(s)))
    add("| **interaction (obs minus motor)** | %d | n/a | %s | %s |" % (
        sum(P["families_leakfree"][f]["n_blocks"] for f in FAMILIES),
        proc(P["interaction_leakfree"]), zero(P["interaction_leakfree"])))
    add("")

    add("## Table IV. Common-horizon check, W = %d ticks" % P["common_window_ticks"])
    add("")
    add("Onset is drawn from [100, 200] and the horizon is 500, so the post-onset window "
        "varies from 300 to 400 ticks by design. W = %d is the longest window every block "
        "can supply in full." % P["common_window_ticks"])
    add("")
    add("| cell | full window | W = %d | shift |" % P["common_window_ticks"])
    add("|---|---|---|---|")
    for c in CELLS:
        a, b = P["cells_full"][c]["point_pp"], P["cells_full_W300"][c]["point_pp"]
        add("| %s | %+.2f | %+.2f | %+.2f |" % (c, a, b, b - a))
    add("")
    add("| family | full window | W = %d, process level (n=%d) | process level |" % (
        P["common_window_ticks"], n_proc))
    add("|---|---|---|---|")
    for f in FAMILIES:
        add("| %s | %+.2f | %s | %s |" % (
            f, P["families_full"][f]["point_pp"], proc(P["families_full_W300"][f]),
            zero(P["families_full_W300"][f])))
    add("")

    add("## Residual contamination")
    add("")
    res = P["residual"]
    add("- pre-onset fall status differs for **%d of %s** disturbed environment pairs "
        "(the pairs the registered estimand uses)"
        % (res["pre_onset_fall_status_differs_disturbed"], f"{res['env_pairs_disturbed']:,}"))
    add("- across **all** environment pairs, disturbed and nominal: **%d of %s**"
        % (res["pre_onset_fall_status_differs_all"], f"{res['env_pairs_all']:,}"))
    add("- blocks affected (disturbed): **%d**; of those, inside the leak-free subset: **%d**"
        % (res["blocks_affected_disturbed"], res["leakfree_disturbed_pairs_with_discrepancy"]))
    add("- by cell: %s" % res["by_cell_disturbed"])
    add("- reset states bit-identical in every arm pair: **%s**"
        % R["reset_states_bit_identical_in_every_replicate"])
    add("- initial observations bit-identical in every arm pair: **%s**"
        % R["initial_observations_bit_identical_in_every_replicate"])
    add("- arm pairs where a single onset-tick threshold separates divergent from "
        "bit-identical blocks with NO exceptions: **%d of %d**"
        % (R["replicates_with_onset_threshold_separation"], R["replicates"]))
    add("- log10 joint probability of that separation under the arbitrary-subset null: "
        "**%.1f**" % R["log10_joint_probability_of_separation_by_chance"])
    add("")

    add("## Onset sensitivity (the only channel by which subset selection can bias)")
    add("")
    add("| cell | slope, pp/tick (process level) | onset shift, ticks | implied bias, pp |")
    add("|---|---|---|---|")
    for c in CELLS:
        o = P["onset_sensitivity"][c]
        b = o["implied_bias_bound_pp"]
        add("| %s | %+.4f [%+.4f, %+.4f] | %+.1f | %+.2f (bound [%+.2f, %+.2f]) |" % (
            c, o["slope_pp_per_tick"], o["slope_lo_pp_per_tick"], o["slope_hi_pp_per_tick"],
            o["mean_onset_shift_divergent_minus_leakfree_ticks"],
            o["implied_extrapolation_bias_pp"], b[0], b[1]))
    add("")

    add("## Subset minus complement (the direct test that the subset is representative)")
    add("")
    add("| cell | delta, pp (process level, n=%d) | crosses zero |" % n_proc)
    add("|---|---|---|")
    for c in CELLS:
        d = P["subset_minus_complement"][c]
        add("| %s | %s | %s |" % (
            c, proc(d), "yes" if not d["excludes_zero"] else "**NO**"))
    add("")

    add("## Table I. Registered gate")
    add("")
    add("| criterion | outcome |")
    add("|---|---|")
    for k, v in S["gate_checks"].items():
        add("| `%s` | %s |" % (k, "PASS" if v else "**FAIL**"))
    add("")

    text = "\n".join(L) + "\n"
    if args.out:
        Path(args.out).write_text(text)
        print("wrote", args.out)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
