#!/usr/bin/env bash
# Run this ON THE PAYLOAD, once per session, before any Phoenix stage.
#
# It does every payload-side step that cost time on 2026-09-17, checks each one
# actually took effect, and writes payload_env.sh so every later terminal is one
# `source` instead of six hand-typed exports.
#
# It moves no motors, starts no bridge, and publishes nothing.
#
# Usage, from the synced repo directory:
#     ./scripts/payload_prep.sh                       # clock left alone
#     ./scripts/payload_prep.sh --utc "2026-09-18 03:14:07"
#     ./scripts/payload_prep.sh --expect-sha <full commit from stage_payload_repo.sh>
#
# Get the UTC string on the WORKSTATION with: date -u +'%Y-%m-%d %H:%M:%S'

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

NIC="${PHOENIX_NIC:-enP8p1s0}"
DDS_XML="$REPO_ROOT/configs/payload/cyclonedds.xml"
ENV_FILE="$REPO_ROOT/payload_env.sh"
UTC=""
EXPECT_SHA=""
BUNDLE="${PHOENIX_BUNDLE:-}"
FAILED=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --utc) [[ $# -ge 2 ]] || { echo "--utc needs a value" >&2; exit 2; }; UTC="$2"; shift 2 ;;
        --expect-sha) [[ $# -ge 2 ]] || { echo "--expect-sha needs a value" >&2; exit 2; }; EXPECT_SHA="$2"; shift 2 ;;
        --bundle) [[ $# -ge 2 ]] || { echo "--bundle needs a value" >&2; exit 2; }; BUNDLE="$2"; shift 2 ;;
        --nic) [[ $# -ge 2 ]] || { echo "--nic needs a value" >&2; exit 2; }; NIC="$2"; shift 2 ;;
        -h|--help) sed -n '2,18p' "$0"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done

step() { printf '\n[prep] == %s\n' "$*"; }
ok()   { printf '[prep] ok   %s\n' "$*"; }
bad()  { printf '[prep] FAIL %s\n' "$*" >&2; FAILED=1; }

# ---------------------------------------------------------------- come-here
step "stop come-here.service (it starves the payload AND can command the robot)"
if ! command -v systemctl >/dev/null 2>&1; then
    bad "no systemctl; cannot prove come-here is stopped. Are you on the payload?"
else
    if [[ "$(systemctl is-active come-here.service 2>/dev/null || true)" == "active" ]]; then
        sudo systemctl stop come-here.service || true
    fi
    state="$(systemctl is-active come-here.service 2>/dev/null || true)"
    if [[ "$state" == "active" ]]; then
        bad "come-here.service is STILL active. Stop it before any stage."
    else
        ok "come-here.service is ${state:-not-loaded}"
    fi
fi

# --------------------------------------------------------------------- clock
step "clock (this payload has no RTC; a wrong clock makes a dead publisher look fresh)"
if [[ -n "$UTC" ]]; then
    sudo date -u -s "$UTC" >/dev/null || bad "could not set the clock"
fi
NOW="$(date -u +'%Y-%m-%d %H:%M:%SZ')"
YEAR="$(date -u +%Y)"
if [[ "$YEAR" -lt 2026 ]]; then
    bad "clock reads $NOW, which is implausible. Re-run with --utc '<workstation date -u>'."
else
    ok "clock reads $NOW"
    [[ -n "$UTC" ]] || printf '[prep] note no --utc given; the clock above was NOT set this session.\n'
fi

# ----------------------------------------------------------------------- DDS
step "CycloneDDS bound to a NIC that exists (a wrong name = every topic empty, list looks fine)"
if [[ ! -f "$DDS_XML" ]]; then
    bad "missing $DDS_XML; the repo sync did not bring configs/payload/"
else
    ok "config $DDS_XML"
    want="$(grep -o 'NetworkInterface name="[^"]*"' "$DDS_XML" | head -1 | sed 's/.*name="\([^"]*\)".*/\1/')"
    if [[ "$want" != "$NIC" ]]; then
        bad "config binds '$want' but this run expects '$NIC'"
    elif ip -brief link show "$NIC" >/dev/null 2>&1; then
        ok "NIC $NIC exists: $(ip -brief link show "$NIC" | awk '{print $2}')"
        ip -brief link show "$NIC" | grep -qi 'UP' || bad "NIC $NIC is not UP"
    else
        bad "NIC $NIC does not exist on this host. Phoenix would see empty topics."
    fi
fi

# -------------------------------------------------------------------- python
step "the payload's python3 imports phoenix from THIS tree"
IMPORTED="$(python3 -c 'import os, phoenix; print(os.path.dirname(os.path.abspath(phoenix.__file__)))' 2>&1 || true)"
if [[ "$IMPORTED" == "$REPO_ROOT/src/phoenix" ]]; then
    ok "phoenix from $IMPORTED"
else
    bad "phoenix imports from '$IMPORTED', expected '$REPO_ROOT/src/phoenix'"
    cat >&2 <<EOF
[prep]      Fix with a .pth entry (do NOT use pip install -e .: this payload's
[prep]      setuptools is 59.6.0, which predates PEP 660 and fails):
[prep]        python3 -c "import site, os; p = site.getusersitepackages(); os.makedirs(p, exist_ok=True); open(os.path.join(p, 'phoenix-dev.pth'), 'w').write('$REPO_ROOT/src' + chr(10)); print(p)"
EOF
fi

# ------------------------------------------------------------------ env file
step "write payload_env.sh"
{
    echo "# Generated by scripts/payload_prep.sh at $NOW. Source this in EVERY terminal."
    echo "# ROS setup.bash uses unbound variables; tolerate that while sourcing it."
    echo "__phoenix_u=\$(set +o | grep nounset); set +u"
    echo "source /opt/ros/humble/setup.bash"
    echo "[ -f \"\$HOME/unitree_ros2/cyclonedds_ws/install/setup.bash\" ] && source \"\$HOME/unitree_ros2/cyclonedds_ws/install/setup.bash\""
    echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp"
    echo "# FILE uri on purpose: unitree_ros2/setup.sh exports inline XML and the harness halts on it."
    echo "export CYCLONEDDS_URI=file://$DDS_XML"
    [[ -n "$EXPECT_SHA" ]] && echo "export PHOENIX_EXPECT_SHA=$EXPECT_SHA"
    [[ -n "$BUNDLE" ]] && echo "export PHOENIX_BUNDLE=$BUNDLE"
    [[ -n "$BUNDLE" ]] && echo "export DEPLOY_CFG=$BUNDLE/deploy_stand_h25.yaml"
    echo "export PHOENIX_DEADMAN=wireless"
    echo "ros2 daemon stop >/dev/null 2>&1 || true   # a stale daemon reports the OLD environment"
    echo "eval \"\$__phoenix_u\"; unset __phoenix_u"
} > "$ENV_FILE"
ok "wrote $ENV_FILE"
[[ -n "$EXPECT_SHA" ]] || printf '[prep] note no --expect-sha given; add PHOENIX_EXPECT_SHA before running any stage.\n'
[[ -n "$BUNDLE" ]] || printf '[prep] note no --bundle given; add PHOENIX_BUNDLE and DEPLOY_CFG before running any stage.\n'

# ----------------------------------------------------------------- contention
step "contention probe (records who else is on the robot; needs the DDS env above)"
# ROS 2's setup.bash references unbound variables (AMENT_TRACE_SETUP_FILES and
# friends), so `set -u` turns sourcing it into a hard error. Relax just for this.
set +u
# shellcheck disable=SC1090
source "$ENV_FILE" || true
set -u
PROBE_OUT="$REPO_ROOT/logs/payload_prep_contention.json"
mkdir -p "$(dirname "$PROBE_OUT")"
rm -f "$PROBE_OUT"
python3 -m phoenix.sim2real.hw_probe contention --out "$PROBE_OUT" >/dev/null 2>&1 || true
if [[ -f "$PROBE_OUT" ]]; then
    python3 - "$PROBE_OUT" <<'PYEOF' || FAILED=1
import json
import sys

from phoenix.sim2real.preflight_eval import contention_checks

probe = json.load(open(sys.argv[1]))
checks = contention_checks(probe)
bad = [c for c in checks if c.gating and not c.ok]
for c in checks:
    print(f"[prep] {'ok  ' if c.ok else 'FAIL'} {c.name}: {c.detail}")
sys.exit(1 if bad else 0)
PYEOF
else
    bad "contention probe wrote nothing; ROS 2 env is not usable yet"
fi

echo
if [[ "$FAILED" -ne 0 ]]; then
    echo "[prep] NOT READY: fix the FAIL lines above, then re-run this script." >&2
    exit 1
fi
cat <<EOF
[prep] READY. In every terminal from now on:

    cd $REPO_ROOT
    source payload_env.sh

Then, motors OFF:
    scripts/harness_preflight.sh A --payload
    scripts/harness_preflight.sh B 30
    scripts/harness_preflight.sh C
    scripts/harness_preflight.sh D 10
    scripts/harness_preflight.sh status     # must say: ready for live hold stage E: YES
EOF
